FROM registry.access.redhat.com/ubi8/ubi:latest as builder
ARG TARGETARCH
RUN dnf clean all && dnf install -y golang
COPY . /perfApp
RUN cd perfApp && GOARCH=${TARGETARCH} CGO_ENABLED=0 go build -o perfApp cmd/perfApp/perfApp.go

FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
MAINTAINER Raúl Sevilla

COPY --from=builder perfApp/perfApp /usr/bin/perfApp
CMD perfApp
