# Use the official Nginx image as the base image
FROM registry.access.redhat.com/ubi8:latest

# Install gettext to provide envsubst command
RUN dnf install -y nginx gettext

# Set environment variable for the port with a default value
ENV LISTEN_PORT=80

# Copy custom Nginx configuration file
COPY nginx.conf.template /etc/nginx/nginx.conf.template

# Expose the port defined by the user
EXPOSE ${LISTEN_PORT}

# Start Nginx with a script that substitutes the port number
CMD envsubst '${LISTEN_PORT}' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'
