FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

RUN microdnf install golang -y \
    && microdnf clean all

WORKDIR /app
COPY go.mod  *.go ./
RUN go mod download
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux go build -o /egressip-validator
EXPOSE 8080
CMD ["/egressip-validator"]
