---
apiVersion: v1
kind: Namespace
metadata:
  name: monitor-eip
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: monitor-eip
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
---      
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: monitor-eip
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
  - kind: ServiceAccount
    name: prometheus-k8s
    namespace: openshift-monitoring
---    
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pod-monitor
  namespace: monitor-eip
spec:
  selector:
    matchLabels:
      app: client
  podMetricsEndpoints:
  - port: metrics
    interval: 15s
    scheme: http
---    
apiVersion: k8s.ovn.org/v1
kind: EgressIP
metadata:
  name: egressip-obj
spec:
  egressIPs:
  - ${EGRESS_IP_ADDRESS}
  namespaceSelector:
    matchLabels:
      kubernetes.io/metadata.name: monitor-eip
  podSelector:
    matchLabels:
      app: client
---      
apiVersion: v1
kind: Pod
metadata:
  name: eip-monitor
  namespace: monitor-eip
  labels:
    app: client
spec:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
  - name: eip-validator
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
    image: quay.io/cloud-bulldozer/eipvalidator:latest
    imagePullPolicy: Always
    env:
    - name: EXT_SERVER_HOST
      value: "${EXT_SERVER_HOST}"
    - name: EXT_SERVER_PORT
      value: "${EXT_SERVER_PORT}"
    - name: EGRESS_IPS
      value: "${EGRESS_IP_ADDRESS}"
    - name: DELAY_BETWEEN_REQ_SEC
      value: "10"
    - name: REQ_TIMEOUT_SEC
      value: "5"
    ports:
    - containerPort: 8080
      name: metrics
    resources:
      requests:
        cpu: "50m"
