name: cloud-bulldozer

on:
  push:
    branches: [ main ]

jobs:

  build-containers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get install qemu-user-static podman fuse-overlayfs

    - name: Login in quay
      run: podman login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Build binary and push containers
      run: make 
