name: cloud-bulldozer

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '**.md'

jobs:

  build-containers:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: sudo apt-get update || true && sudo apt-get install -y qemu-user-static podman fuse-overlayfs

    - name: Login in quay
      if: github.event_name == 'push'
      run: podman login quay.io -u ${QUAY_USER} -p ${QUAY_TOKEN}
      env:
        QUAY_USER: ${{ secrets.QUAY_USER }}
        QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}

    - name: Build containers only (PR)
      if: github.event_name == 'pull_request'
      run: make build

    - name: Build and push containers (main branch)
      if: github.event_name == 'push'
      run: make 
